// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    } else if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    } else {
      throw UnsupportedError(
        'DefaultFirebaseOptions are only configured for web and Android.',
      );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Sg2Gjm3WdfbPVzf4pKmP-wROGtKR9Nk',
    appId: '1:311690882404:web:79d5f537da0ea5aefe1e71',
    messagingSenderId: '311690882404',
    projectId: 'foodapp-b2580',
    authDomain: 'foodapp-b2580.firebaseapp.com',
    storageBucket: 'foodapp-b2580.appspot.com',
    measurementId: 'G-J1NE4KKLG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_vO6avVdO8h5qXXaH3nvFydVsqg7wPQE',
    appId: '1:311690882404:android:0197fa5dc8f53549fe1e71',
    messagingSenderId: '311690882404',
    projectId: 'foodapp-b2580',
    storageBucket: 'foodapp-b2580.appspot.com',
  );

}